config/routes.rb
Rails.application.routes.draw do


  root 'shots#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :users
  resources :shots
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #root 'shots#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shot.rb
class Shot < ApplicationRecord
    has_one_attached :image
    validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: %i[ show edit update destroy ]

  # GET /shots or /shots.json
  def index
    @shots = Shot.all
  end

  # GET /shots/1 or /shots/1.json
  def show
    @shot = Shot.find(params[:id])
  end

  # GET /shots/new
  def new
    @shot = Shot.new
  end

  # GET /shots/1/edit
  def edit
    @shot = Shot.find(params[:id])
  end

  # POST /shots or /shots.json
  def create
    @shot = Shot.new(shot_params)
    @shot.image.attach(params[:shot][:image]) # Attach the image here
    if @shot.save
      redirect_to @shot, notice: 'Shot was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /shots/1 or /shots/1.json
  def update
    if @shot.update(shot_params)
      @shot.image.attach(params[:shot][:image]) # Attach the image here
      redirect_to @shot, notice: 'Shot was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /shots/1 or /shots/1.json
  def destroy
    @shot.destroy

    respond_to do |format|
      format.html { redirect_to shots_url, notice: "Shot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shot_params
      params.require(:shot).permit(:title, :description, :image)
    end
end

app/controllers/users/registrations_controller.rb
# app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :configure_account_update_params, only: [:update]

    protected

    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:work_preferences, :settings])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_hero.html.erb
<div class="py-16 bg-blue-500">
  <div class="container mx-auto text-center text-white">
    <h1 class="mb-4 text-4xl font-semibold">Discover Creative Designs</h1>
    <p class="mb-8 text-lg">Explore a world of stunning visual creations.</p>
    <a href="/shots" class="px-6 py-3 font-semibold text-blue-500 bg-white rounded-md hover:bg-blue-100 hover:text-blue-700">Browse Shots</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DribbbleClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/hero' %>
    <main class="container flex px-5 mx-auto mt-28">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shots/_form.html.erb
 
<%= form_with(model: shot) do |form| %>
  <% if shot.errors.any? %>
   <div id="error_explanation" class="p-4 mb-4 text-red-700 bg-red-100 rounded">
      <h2 class="font-semibold"><%= pluralize(shot.errors.count, "error") %> prohibited this shot from being saved:</h2>

      <ul class="mt-2 list-disc list-inside">
        <% shot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "block font-semibold text-gray-800" %>
    <%= form.text_field :title %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block font-semibold text-gray-800" %>
    <%= form.text_area :description , class: "form-textarea mt-1 block w-full"%>
  </div>

  <div class="mb-4">
  <%= form.label :image, "Upload Image", class: "block font-semibold text-gray-800" %>
  <%= form.file_field :image, accept: "image/*", class: "form-input mt-1 block w-full" %>
</div>

  <div class="mt-6">
    <%= form.submit "Save", class: "px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600" %>
  </div>
<% end %>

app/views/shots/_shot.html.erb
<div class="max-w-md p-6 mx-auto bg-white rounded-lg shadow-md">
    <%= image_tag @shot.image, class: "w-full rounded-t-lg" %>
    <h2 class="mt-4 text-xl font-semibold"><%= @shot.title %></h2>
     <p class="mt-2 text-gray-600"><%= @shot.description %></p>
</div>

app/views/shots/edit.html.erb
<div class="flex flex-wrap justify-center">
<h1 class="mx-2 text-3xl font-bold text-indigo-300">Editing shot</h1>

<%= render "form", shot: @shot %>

<br>

<div>
  <%= link_to "Show this shot", @shot %> |
  <%= link_to "Back to shots", shots_path %>
</div>
</div>

app/views/shots/index.html.erb
<div class="flex flex-wrap justify-center">
  <% @shots.each do |shot| %>
    <div class="max-w-xs mx-4 my-6 bg-white rounded-lg shadow-md">
      <%=  image_tag url_for(shot.image), class: "w-full rounded-t-lg" %>
      <div class="p-4">
        <h2 class="text-lg font-semibold"><%= shot.title %></h2>
        <p class="mt-2 text-gray-600"><%= shot.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/shots/new.html.erb
<div class="justify-center d-flex">
<h1 class="text-3xl font-bold text-indigo-300">New shot</h1>

<%= render "form", shot: @shot %>

<br>

<div>
  <%= link_to "Back to shots", shots_path, class: "inline-block px-4 py-2 bg-gray-500 text-white rounded-md hover:bg-gray-600"  %>
</div>
</div>

app/views/shots/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="flex ">
<div class="flex flex-wrap justify-center">
<%= render @shot %>

<div class="">
  <%= link_to "Edit this shot", edit_shot_path(@shot) %> |
  <%= link_to "Back to shots", shots_path %> |

  <%= button_to "Destroy this shot", @shot, method: :delete %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
<div>
  <h1>Profile</h1>
  <p>Work Preferences: <%= @user.work_preferences %></p>
  <p>Settings: <%= @user.settings %></p>

  <%= link_to "Edit Profile", edit_user_registration_path, class: "block p-4 text-xl font-semibold text-gray-400 rounded hover:bg-blue-50 hover:text-blue-600" %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "block p-4 text-xl font-semibold text-gray-400 rounded hover:bg-blue-50 hover:text-blue-600 " %>
</div>